-- 数据迁移脚本：将 QualityStatus 从字符串转换为枚举值
-- 执行前请备份数据库

-- 1. 首先添加新的临时列
ALTER TABLE LAB_INTERMEDIATE_DATA_JUDGMENT_LEVEL 
ADD F_QUALITY_STATUS_NEW INT DEFAULT 2;

-- 2. 将现有字符串数据转换为枚举值
--    Qualified = 0
--    Unqualified = 1
--    Other = 2

UPDATE LAB_INTERMEDIATE_DATA_JUDGMENT_LEVEL 
SET F_QUALITY_STATUS_NEW = CASE 
    WHEN F_QUALITY_STATUS = '合格' THEN 0
    WHEN F_QUALITY_STATUS = '不合格' THEN 1
    ELSE 2
END;

-- 3. 删除旧列
ALTER TABLE LAB_INTERMEDIATE_DATA_JUDGMENT_LEVEL 
DROP COLUMN F_QUALITY_STATUS;

-- 4. 重命名新列为原列名
-- 注意：不同数据库语法可能不同
-- MySQL:
ALTER TABLE LAB_INTERMEDIATE_DATA_JUDGMENT_LEVEL 
CHANGE COLUMN F_QUALITY_STATUS_NEW F_QUALITY_STATUS INT DEFAULT 2;

-- SQL Server 使用:
-- EXEC sp_rename 'LAB_INTERMEDIATE_DATA_JUDGMENT_LEVEL.F_QUALITY_STATUS_NEW', 'F_QUALITY_STATUS', 'COLUMN';

-- PostgreSQL 使用:
-- ALTER TABLE LAB_INTERMEDIATE_DATA_JUDGMENT_LEVEL 
-- RENAME COLUMN F_QUALITY_STATUS_NEW TO F_QUALITY_STATUS;

-- 5. 验证数据迁移结果
SELECT 
    COUNT(*) as total,
    SUM(CASE WHEN F_QUALITY_STATUS = 0 THEN 1 ELSE 0 END) as qualified_count,
    SUM(CASE WHEN F_QUALITY_STATUS = 1 THEN 1 ELSE 0 END) as unqualified_count,
    SUM(CASE WHEN F_QUALITY_STATUS = 2 THEN 1 ELSE 0 END) as other_count
FROM LAB_INTERMEDIATE_DATA_JUDGMENT_LEVEL;
