export const datamodels = {
  code: '000',
  data: {
    list: [
      {
        id: 'dmag7fdlrtg',
        created: 1699260405508,
        last_modified: 1699260650881,
        type: 'TABLE',
        name: 'retail_stores_by_transaction',
        display_name: '零售数据表',
        owner_name: '13051762363',
        owner_display_name: '姜东',
        owner_id: '244502774363828226',
        access_level: 'ADMIN',
        cached: false,
        modeled: true,
        connection_id: 'conds9fdlrtg',
        connection: {
          name: 'file_retail_stores_by_transaction_1699260405329_dm5yms',
          display_name: 'file:retail_stores_by_transaction_IZrFdx',
          description: null,
          type: 'FILE',
          properties: {
            file_type: 'CSV',
            origin_source: 'UPLOAD',
            storage_folder:
              'tenant-244502774363828225/Zen/244502774363828226/datasources/csv/file_retail_stores_by_transaction_1699260405329_dm5yms/',
          },
        },
        columns: [
          {
            name: '订单编号',
            origin_name: '订单编号',
            type: 'STRING',
            origin_type: 'VARCHAR',
            date_pattern: null,
            expression: null,
            desc: null,
            samples: [
              'TUID-1',
              'TUID-2',
              'TUID-3',
              'TUID-4',
              'TUID-5',
              'TUID-6',
              'TUID-7',
              'TUID-8',
              'TUID-9',
              'TUID-10',
            ],
          },
          {
            name: '订单日期',
            origin_name: '订单日期',
            type: 'DATE',
            origin_type: 'DATE',
            date_pattern: 'yyyy/MM/dd',
            expression: null,
            desc: null,
            samples: [
              '2017-11-08',
              '2017-11-08',
              '2017-06-12',
              '2016-10-11',
              '2016-10-11',
              '2015-06-09',
              '2015-06-09',
              '2015-06-09',
              '2015-06-09',
              '2015-06-09',
            ],
          },
          {
            name: '订单年份',
            origin_name: '订单年份',
            type: 'INT',
            origin_type: 'INT',
            date_pattern: null,
            expression: null,
            desc: null,
            samples: ['2017', '2017', '2017', '2016', '2016', '2015', '2015', '2015', '2015', '2015'],
          },
          {
            name: '订单月份',
            origin_name: '订单月份',
            type: 'INT',
            origin_type: 'INT',
            date_pattern: null,
            expression: null,
            desc: null,
            samples: ['11', '11', '6', '10', '10', '6', '6', '6', '6', '6'],
          },
          {
            name: '订单天数',
            origin_name: '订单天数',
            type: 'INT',
            origin_type: 'INT',
            date_pattern: null,
            expression: null,
            desc: null,
            samples: ['8', '8', '12', '11', '11', '9', '9', '9', '9', '9'],
          },
          {
            name: '客户名称',
            origin_name: '客户名称',
            type: 'STRING',
            origin_type: 'VARCHAR',
            date_pattern: null,
            expression: null,
            desc: null,
            samples: ['莱利', '菲利斯', '安东', '玛丽', '塔卡梅', '加兰德', '罗斯', '拉托尼亚', '拉托尼亚', '朗尼'],
          },
          {
            name: '门店区域',
            origin_name: '门店区域',
            type: 'STRING',
            origin_type: 'VARCHAR',
            date_pattern: null,
            expression: null,
            desc: null,
            samples: ['北部', '南部', '西部', '南部', '南部', '西部', '西部', '西部', '西部', '西部'],
          },
          {
            name: '门店城市',
            origin_name: '门店城市',
            type: 'STRING',
            origin_type: 'VARCHAR',
            date_pattern: null,
            expression: null,
            desc: null,
            samples: [
              '波特兰',
              '夏延',
              '海伦娜',
              '俾斯麦',
              '夏威夷',
              '俾斯麦',
              '凤凰城',
              '印第安纳波利斯',
              '费城',
              '亚特兰大',
            ],
          },
          {
            name: '商品分类',
            origin_name: '商品分类',
            type: 'STRING',
            origin_type: 'VARCHAR',
            date_pattern: null,
            expression: null,
            desc: null,
            samples: [
              '油 & 香料',
              '饮料',
              '粮食',
              '水果 & 蔬菜',
              '粮食',
              '粮食',
              '水果 & 蔬菜',
              '水果 & 蔬菜',
              '面包',
              '面包',
            ],
          },
          {
            name: '商品单价',
            origin_name: '商品单价',
            type: 'INT',
            origin_type: 'INT',
            date_pattern: null,
            expression: null,
            desc: null,
            samples: ['1254', '749', '2360', '896', '2355', '2305', '826', '1847', '791', '1795'],
          },
          {
            name: '商品折扣',
            origin_name: '商品折扣',
            type: 'DOUBLE',
            origin_type: 'DOUBLE',
            date_pattern: null,
            expression: null,
            desc: null,
            samples: ['0.12', '0.18', '0.21', '0.25', '0.26', '0.26', '0.33', '0.32', '0.23', '0.27'],
          },
          {
            name: '商品数量',
            origin_name: '商品数量',
            type: 'INT',
            origin_type: 'INT',
            date_pattern: null,
            expression: null,
            desc: null,
            samples: ['2', '1', '1', '5', '4', '4', '3', '1', '5', '4'],
          },
          {
            name: '订单净利润',
            origin_name: '订单净利润',
            type: 'DOUBLE',
            origin_type: 'DOUBLE',
            date_pattern: null,
            expression: null,
            desc: null,
            samples: ['401.28', '149.8', '165.2', '89.6', '918.45', '322.7', '346.92', '147.76', '181.93', '484.65'],
          },
        ],
        properties: {
          escape: '\\',
          header: 'true',
          delimiter: ',',
          row_count: '9994',
          storage_location:
            's3://zen-prod-202311/tenant-244502774363828225/Zen/244502774363828226/datasources/csv/file_retail_stores_by_transaction_1699260405329_dm5yms',
          storage_file_size: '861726',
          storage_content_md5: 'bbdce1cc14a06c148579c0b45e80c1d2',
          storage_last_modified: '1699260406000',
        },
        tables: null,
        joins: null,
        dimensions: [
          {
            id: 'dimo8afdlrtg',
            name: '商品分类',
            display_name: '商品分类',
            group: 'retail_stores_by_transaction',
            display_group: '零售数据表',
            type: 'STRING',
            links: [],
            display_links: [],
            ref: '商品分类',
            last_modified: 1699260405553,
            created: 1699260405510,
            alias_name: '姜东',
            user_id: '244502774363828226',
          },
          {
            id: 'dimp8afdlrtg',
            name: '商品单价',
            display_name: '商品单价',
            group: 'retail_stores_by_transaction',
            display_group: '零售数据表',
            type: 'INT',
            links: [],
            display_links: [],
            ref: '商品单价',
            last_modified: 1699260405553,
            created: 1699260405510,
            alias_name: '姜东',
            user_id: '244502774363828226',
          },
          {
            id: 'dimq8afdlrtg',
            name: '商品折扣',
            display_name: '商品折扣',
            group: 'retail_stores_by_transaction',
            display_group: '零售数据表',
            type: 'DOUBLE',
            links: [],
            display_links: [],
            ref: '商品折扣',
            last_modified: 1699260405553,
            created: 1699260405510,
            alias_name: '姜东',
            user_id: '244502774363828226',
          },
          {
            id: 'dimr8afdlrtg',
            name: '商品数量',
            display_name: '商品数量',
            group: 'retail_stores_by_transaction',
            display_group: '零售数据表',
            type: 'INT',
            links: [],
            display_links: [],
            ref: '商品数量',
            last_modified: 1699260405553,
            created: 1699260405510,
            alias_name: '姜东',
            user_id: '244502774363828226',
          },
          {
            id: 'dims8afdlrtg',
            name: '客户名称',
            display_name: '客户名称',
            group: 'retail_stores_by_transaction',
            display_group: '零售数据表',
            type: 'STRING',
            links: [],
            display_links: [],
            ref: '客户名称',
            last_modified: 1699260405553,
            created: 1699260405510,
            alias_name: '姜东',
            user_id: '244502774363828226',
          },
          {
            id: 'dimt8afdlrtg',
            name: '订单净利润',
            display_name: '订单净利润',
            group: 'retail_stores_by_transaction',
            display_group: '零售数据表',
            type: 'DOUBLE',
            links: [],
            display_links: [],
            ref: '订单净利润',
            last_modified: 1699260405553,
            created: 1699260405510,
            alias_name: '姜东',
            user_id: '244502774363828226',
          },
          {
            id: 'dimu8afdlrtg',
            name: '订单天数',
            display_name: '订单天数',
            group: 'retail_stores_by_transaction',
            display_group: '零售数据表',
            type: 'INT',
            links: [],
            display_links: [],
            ref: '订单天数',
            last_modified: 1699260405553,
            created: 1699260405510,
            alias_name: '姜东',
            user_id: '244502774363828226',
          },
          {
            id: 'dimv8afdlrtg',
            name: '订单年份',
            display_name: '订单年份',
            group: 'retail_stores_by_transaction',
            display_group: '零售数据表',
            type: 'INT',
            links: [],
            display_links: [],
            ref: '订单年份',
            last_modified: 1699260405553,
            created: 1699260405510,
            alias_name: '姜东',
            user_id: '244502774363828226',
          },
          {
            id: 'dimw8afdlrtg',
            name: '订单日期',
            display_name: '订单日期',
            group: 'retail_stores_by_transaction',
            display_group: '零售数据表',
            type: 'DATE',
            links: [],
            display_links: [],
            ref: '订单日期',
            last_modified: 1699260405553,
            created: 1699260405510,
            alias_name: '姜东',
            user_id: '244502774363828226',
          },
          {
            id: 'dim38afdlrtg',
            name: '订单月份',
            display_name: '订单月份',
            group: 'retail_stores_by_transaction',
            display_group: '零售数据表',
            type: 'INT',
            links: [],
            display_links: [],
            ref: '订单月份',
            last_modified: 1699260405553,
            created: 1699260405510,
            alias_name: '姜东',
            user_id: '244502774363828226',
          },
          {
            id: 'dim28afdlrtg',
            name: '订单编号',
            display_name: '订单编号',
            group: 'retail_stores_by_transaction',
            display_group: '零售数据表',
            type: 'STRING',
            links: [],
            display_links: [],
            ref: '订单编号',
            last_modified: 1699260405553,
            created: 1699260405510,
            alias_name: '姜东',
            user_id: '244502774363828226',
          },
          {
            id: 'dim18afdlrtg',
            name: '门店区域',
            display_name: '门店区域',
            group: 'retail_stores_by_transaction',
            display_group: '零售数据表',
            type: 'STRING',
            links: [],
            display_links: [],
            ref: '门店区域',
            last_modified: 1699260405553,
            created: 1699260405510,
            alias_name: '姜东',
            user_id: '244502774363828226',
          },
          {
            id: 'dimx8afdlrtg',
            name: '门店城市',
            display_name: '门店城市',
            group: 'retail_stores_by_transaction',
            display_group: '零售数据表',
            type: 'STRING',
            links: [],
            display_links: [],
            ref: '门店城市',
            last_modified: 1699260405553,
            created: 1699260405510,
            alias_name: '姜东',
            user_id: '244502774363828226',
          },
        ],
        metrics_count: 22,
        query_count: 58,
        row_count: 9994,
        file_origin_sources: 'UPLOAD',
        file_total_size: 861726,
        cache_status: 'OFF',
        notes: null,
      },
    ],
    total_size: 1,
  },
  message: null,
};

export const model_data_value = {
  code: '000',
  data: {
    query_id: '0739ab62-b9fa-4d90-bc6d-1f37ea0b1bcd',
    total_time: 14,
    fetch_data_query_ids: null,
    fetch_data_time: 14,
    executed_sqls: [
      'SELECT * FROM (select 商品分类\nfrom default_8unqpwn8.retail_stores_by_transaction\ngroup by 商品分类\norder by 商品分类\nlimit 2147483647) AS "1699260406000"',
    ],
    metas: [
      {
        name: '商品分类',
        data_type: 'VARCHAR',
      },
    ],
    data: [['水果 & 蔬菜'], ['油 & 香料'], ['点心'], ['粮食'], ['肉类 & 鱼类'], ['面包'], ['饮料']],
    hit_realizations: {},
    data_last_update_time: null,
  },
  message: null,
};

export const model_data_number = {
  code: '000',
  data: {
    query_id: 'b0118bc9-c1b7-46bd-b7c6-9fab0ba078f8',
    total_time: 320,
    fetch_data_query_ids: null,
    fetch_data_time: 320,
    executed_sqls: [
      'SELECT * FROM (select 商品折扣\nfrom default_8unqpwn8.retail_stores_by_transaction\ngroup by 商品折扣\norder by 商品折扣\nlimit 2147483647) AS "1699260406000"',
    ],
    metas: [
      {
        name: '商品折扣',
        data_type: 'DOUBLE',
      },
    ],
    data: [
      ['0.1'],
      ['0.11'],
      ['0.12'],
      ['0.13'],
      ['0.14'],
      ['0.15'],
      ['0.16'],
      ['0.17'],
      ['0.18'],
      ['0.19'],
      ['0.2'],
      ['0.21'],
      ['0.22'],
      ['0.23'],
      ['0.24'],
      ['0.25'],
      ['0.26'],
      ['0.27'],
      ['0.28'],
      ['0.29'],
      ['0.3'],
      ['0.31'],
      ['0.32'],
      ['0.33'],
      ['0.34'],
      ['0.35'],
    ],
    hit_realizations: {},
    data_last_update_time: null,
  },
  message: null,
};

export const model_data_tags = [
  {
    code: '000',
    data: {
      list: [
        {
          id: 'tagqeqfkk4yg',
          name: '1234',
          metric_count: null,
          data_product_count: null,
        },
        {
          id: 'tag8h53j2sug',
          name: '3311',
          metric_count: null,
          data_product_count: null,
        },
        {
          id: 'tag2txzdlrtg',
          name: '样例数据',
          metric_count: 22,
          data_product_count: 4,
        },
      ],
      total_size: 3,
    },
    message: null,
  },
];
