-- 迁移脚本：将班次字段从数字改为字符串，新增班次数字字段用于排序
-- 执行前请备份数据

-- 1. 添加班次数字字段
ALTER TABLE LAB_RAW_DATA ADD COLUMN F_SHIFT_NUMERIC INT NULL COMMENT '班次数字（用于排序：甲=1, 乙=2, 丙=3）';

-- 2. 备份现有的班次数据到新的数字字段
UPDATE LAB_RAW_DATA SET F_SHIFT_NUMERIC = F_SHIFT WHERE F_SHIFT IS NOT NULL;

-- 3. 修改班次字段类型为字符串
ALTER TABLE LAB_RAW_DATA MODIFY COLUMN F_SHIFT VARCHAR(10) NULL COMMENT '班次（甲、乙、丙）';

-- 4. 将数字转换为汉字
UPDATE LAB_RAW_DATA SET F_SHIFT = '甲' WHERE F_SHIFT_NUMERIC = 1;
UPDATE LAB_RAW_DATA SET F_SHIFT = '乙' WHERE F_SHIFT_NUMERIC = 2;
UPDATE LAB_RAW_DATA SET F_SHIFT = '丙' WHERE F_SHIFT_NUMERIC = 3;

-- 验证结果
SELECT F_SHIFT, F_SHIFT_NUMERIC, COUNT(*) as cnt FROM LAB_RAW_DATA GROUP BY F_SHIFT, F_SHIFT_NUMERIC;
