-- ============================================
-- 中间数据表 - 扩展带厚和叠片系数分布字段
-- 说明:
--   1. 新增 F_THICKNESS_11 到 F_THICKNESS_22 字段（带厚分布）
--   2. 新增 F_LAMINATION_DIST_11 到 F_LAMINATION_DIST_22 字段（叠片系数分布）
--   3. 支持最多22个检测点的数据存储
-- 创建时间: 2026-01-19
-- ============================================

-- ============================================
-- MySQL版本
-- ============================================

-- 添加带厚分布字段 (11-22)
ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_THICKNESS_11` DECIMAL(18, 2) NULL COMMENT '带厚11'
AFTER `F_THICKNESS_10`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_THICKNESS_12` DECIMAL(18, 2) NULL COMMENT '带厚12'
AFTER `F_THICKNESS_11`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_THICKNESS_13` DECIMAL(18, 2) NULL COMMENT '带厚13'
AFTER `F_THICKNESS_12`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_THICKNESS_14` DECIMAL(18, 2) NULL COMMENT '带厚14'
AFTER `F_THICKNESS_13`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_THICKNESS_15` DECIMAL(18, 2) NULL COMMENT '带厚15'
AFTER `F_THICKNESS_14`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_THICKNESS_16` DECIMAL(18, 2) NULL COMMENT '带厚16'
AFTER `F_THICKNESS_15`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_THICKNESS_17` DECIMAL(18, 2) NULL COMMENT '带厚17'
AFTER `F_THICKNESS_16`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_THICKNESS_18` DECIMAL(18, 2) NULL COMMENT '带厚18'
AFTER `F_THICKNESS_17`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_THICKNESS_19` DECIMAL(18, 2) NULL COMMENT '带厚19'
AFTER `F_THICKNESS_18`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_THICKNESS_20` DECIMAL(18, 2) NULL COMMENT '带厚20'
AFTER `F_THICKNESS_19`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_THICKNESS_21` DECIMAL(18, 2) NULL COMMENT '带厚21'
AFTER `F_THICKNESS_20`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_THICKNESS_22` DECIMAL(18, 2) NULL COMMENT '带厚22'
AFTER `F_THICKNESS_21`;

-- 添加叠片系数分布字段 (11-22)
ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_LAMINATION_DIST_11` DECIMAL(18, 2) NULL COMMENT '叠片系数分布11'
AFTER `F_LAMINATION_DIST_10`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_LAMINATION_DIST_12` DECIMAL(18, 2) NULL COMMENT '叠片系数分布12'
AFTER `F_LAMINATION_DIST_11`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_LAMINATION_DIST_13` DECIMAL(18, 2) NULL COMMENT '叠片系数分布13'
AFTER `F_LAMINATION_DIST_12`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_LAMINATION_DIST_14` DECIMAL(18, 2) NULL COMMENT '叠片系数分布14'
AFTER `F_LAMINATION_DIST_13`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_LAMINATION_DIST_15` DECIMAL(18, 2) NULL COMMENT '叠片系数分布15'
AFTER `F_LAMINATION_DIST_14`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_LAMINATION_DIST_16` DECIMAL(18, 2) NULL COMMENT '叠片系数分布16'
AFTER `F_LAMINATION_DIST_15`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_LAMINATION_DIST_17` DECIMAL(18, 2) NULL COMMENT '叠片系数分布17'
AFTER `F_LAMINATION_DIST_16`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_LAMINATION_DIST_18` DECIMAL(18, 2) NULL COMMENT '叠片系数分布18'
AFTER `F_LAMINATION_DIST_17`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_LAMINATION_DIST_19` DECIMAL(18, 2) NULL COMMENT '叠片系数分布19'
AFTER `F_LAMINATION_DIST_18`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_LAMINATION_DIST_20` DECIMAL(18, 2) NULL COMMENT '叠片系数分布20'
AFTER `F_LAMINATION_DIST_19`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_LAMINATION_DIST_21` DECIMAL(18, 2) NULL COMMENT '叠片系数分布21'
AFTER `F_LAMINATION_DIST_20`;

ALTER TABLE `LAB_INTERMEDIATE_DATA`
ADD COLUMN `F_LAMINATION_DIST_22` DECIMAL(18, 2) NULL COMMENT '叠片系数分布22'
AFTER `F_LAMINATION_DIST_21`;

-- ============================================
-- 数据迁移说明
-- ============================================
-- 1. 新添加的字段默认为NULL，不影响现有数据
-- 2. 当产品规格配置了更多检测点（超过10个）时，系统会自动使用新字段
-- 3. 现有中间数据需要重新生成才能填充新字段（通过中间数据生成功能）