-- 为 LAB_SEVERITY_LEVEL 表添加 F_ISDEFAULT 字段
-- 执行日期: 2026-01-10
-- 说明: 添加是否默认字段，用于标识默认的严重程度等级

-- MySQL
ALTER TABLE `LAB_SEVERITY_LEVEL` 
ADD COLUMN `F_ISDEFAULT` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否默认' AFTER `F_ENABLED`;

-- 如果需要支持其他数据库，可以添加相应的 SQL：
-- SQL Server
-- ALTER TABLE [LAB_SEVERITY_LEVEL] 
-- ADD [F_ISDEFAULT] BIT NOT NULL DEFAULT 0;

-- PostgreSQL
-- ALTER TABLE "LAB_SEVERITY_LEVEL" 
-- ADD COLUMN "F_ISDEFAULT" BOOLEAN NOT NULL DEFAULT FALSE;
