-- 修改 LAB_SEVERITY_LEVEL 表的 F_DESCRIPTION 字段，允许 NULL
-- 执行日期: 2026-01-10
-- 说明: 将 F_DESCRIPTION 字段从 NOT NULL 改为允许 NULL

-- MySQL
ALTER TABLE `LAB_SEVERITY_LEVEL` 
MODIFY COLUMN `F_DESCRIPTION` VARCHAR(200) NULL COMMENT '等级描述（可为空）';
