-- ============================================
-- 删除 F_DETECTION_1 到 F_DETECTION_22 字段
-- 说明：这些字段已被 F_DETECTION_DATA JSON 字段替代
-- 执行日期：2025-01-XX
-- ============================================

-- 删除 LAB_RAW_DATA 表中的检测列字段
ALTER TABLE `LAB_RAW_DATA`
  DROP COLUMN `F_DETECTION_1`,
  DROP COLUMN `F_DETECTION_2`,
  DROP COLUMN `F_DETECTION_3`,
  DROP COLUMN `F_DETECTION_4`,
  DROP COLUMN `F_DETECTION_5`,
  DROP COLUMN `F_DETECTION_6`,
  DROP COLUMN `F_DETECTION_7`,
  DROP COLUMN `F_DETECTION_8`,
  DROP COLUMN `F_DETECTION_9`,
  DROP COLUMN `F_DETECTION_10`,
  DROP COLUMN `F_DETECTION_11`,
  DROP COLUMN `F_DETECTION_12`,
  DROP COLUMN `F_DETECTION_13`,
  DROP COLUMN `F_DETECTION_14`,
  DROP COLUMN `F_DETECTION_15`,
  DROP COLUMN `F_DETECTION_16`,
  DROP COLUMN `F_DETECTION_17`,
  DROP COLUMN `F_DETECTION_18`,
  DROP COLUMN `F_DETECTION_19`,
  DROP COLUMN `F_DETECTION_20`,
  DROP COLUMN `F_DETECTION_21`,
  DROP COLUMN `F_DETECTION_22`;

-- 验证：检查字段是否已删除
-- SELECT COLUMN_NAME 
-- FROM INFORMATION_SCHEMA.COLUMNS 
-- WHERE TABLE_SCHEMA = DATABASE() 
--   AND TABLE_NAME = 'LAB_RAW_DATA' 
--   AND COLUMN_NAME LIKE 'F_DETECTION_%';
