-- =============================================
-- 修改数据库 decimal 字段精度为 6 位小数
-- 执行前请备份数据
-- =============================================

-- =============================================
-- 1. LAB_RAW_DATA 表 (RawDataEntity)
-- =============================================
ALTER TABLE `LAB_RAW_DATA` 
    MODIFY COLUMN `F_WIDTH` DECIMAL(18,6) NULL COMMENT '宽度',
    MODIFY COLUMN `F_COIL_WEIGHT` DECIMAL(18,6) NULL COMMENT '带材重量',
    MODIFY COLUMN `F_SINGLE_COIL_WEIGHT` DECIMAL(18,6) NULL COMMENT '单卷重量(kg)',
    MODIFY COLUMN `F_DETECTION_1` DECIMAL(18,6) NULL COMMENT '检测1',
    MODIFY COLUMN `F_DETECTION_2` DECIMAL(18,6) NULL COMMENT '检测2',
    MODIFY COLUMN `F_DETECTION_3` DECIMAL(18,6) NULL COMMENT '检测3',
    MODIFY COLUMN `F_DETECTION_4` DECIMAL(18,6) NULL COMMENT '检测4',
    MODIFY COLUMN `F_DETECTION_5` DECIMAL(18,6) NULL COMMENT '检测5',
    MODIFY COLUMN `F_DETECTION_6` DECIMAL(18,6) NULL COMMENT '检测6',
    MODIFY COLUMN `F_DETECTION_7` DECIMAL(18,6) NULL COMMENT '检测7',
    MODIFY COLUMN `F_DETECTION_8` DECIMAL(18,6) NULL COMMENT '检测8',
    MODIFY COLUMN `F_DETECTION_9` DECIMAL(18,6) NULL COMMENT '检测9',
    MODIFY COLUMN `F_DETECTION_10` DECIMAL(18,6) NULL COMMENT '检测10',
    MODIFY COLUMN `F_DETECTION_11` DECIMAL(18,6) NULL COMMENT '检测11',
    MODIFY COLUMN `F_DETECTION_12` DECIMAL(18,6) NULL COMMENT '检测12',
    MODIFY COLUMN `F_DETECTION_13` DECIMAL(18,6) NULL COMMENT '检测13',
    MODIFY COLUMN `F_DETECTION_14` DECIMAL(18,6) NULL COMMENT '检测14',
    MODIFY COLUMN `F_DETECTION_15` DECIMAL(18,6) NULL COMMENT '检测15',
    MODIFY COLUMN `F_DETECTION_16` DECIMAL(18,6) NULL COMMENT '检测16',
    MODIFY COLUMN `F_DETECTION_17` DECIMAL(18,6) NULL COMMENT '检测17',
    MODIFY COLUMN `F_DETECTION_18` DECIMAL(18,6) NULL COMMENT '检测18',
    MODIFY COLUMN `F_DETECTION_19` DECIMAL(18,6) NULL COMMENT '检测19',
    MODIFY COLUMN `F_DETECTION_20` DECIMAL(18,6) NULL COMMENT '检测20',
    MODIFY COLUMN `F_DETECTION_21` DECIMAL(18,6) NULL COMMENT '检测21',
    MODIFY COLUMN `F_DETECTION_22` DECIMAL(18,6) NULL COMMENT '检测22';

-- =============================================
-- 2. LAB_MAGNETIC_RAW_DATA 表 (MagneticRawDataEntity)
-- =============================================
ALTER TABLE `LAB_MAGNETIC_RAW_DATA` 
    MODIFY COLUMN `F_PS_LOSS` DECIMAL(18,6) NULL COMMENT 'Ps铁损',
    MODIFY COLUMN `F_SS_POWER` DECIMAL(18,6) NULL COMMENT 'Ss激磁功率',
    MODIFY COLUMN `F_HC` DECIMAL(18,6) NULL COMMENT 'Hc';

-- =============================================
-- 3. LAB_INTERMEDIATE_DATA 表 (IntermediateDataEntity)
-- =============================================

-- 3.1 性能数据
ALTER TABLE `LAB_INTERMEDIATE_DATA` 
    MODIFY COLUMN `F_PERF_SS_POWER` DECIMAL(18,6) NULL COMMENT '1.35T 50Hz Ss激磁功率 (VA/kg)',
    MODIFY COLUMN `F_PERF_PS_LOSS` DECIMAL(18,6) NULL COMMENT '1.35T 50Hz Ps铁损 (W/kg)',
    MODIFY COLUMN `F_PERF_HC` DECIMAL(18,6) NULL COMMENT '1.35T 50Hz Hc (A/m)',
    MODIFY COLUMN `F_AFTER_SS_POWER` DECIMAL(18,6) NULL COMMENT '刻痕后性能 Ss激磁功率',
    MODIFY COLUMN `F_AFTER_PS_LOSS` DECIMAL(18,6) NULL COMMENT '刻痕后性能 Ps铁损',
    MODIFY COLUMN `F_AFTER_HC` DECIMAL(18,6) NULL COMMENT '刻痕后性能 Hc';

-- 3.2 物理特性
ALTER TABLE `LAB_INTERMEDIATE_DATA` 
    MODIFY COLUMN `F_ONE_METER_WT` DECIMAL(18,6) NULL COMMENT '一米带材重量(g)',
    MODIFY COLUMN `F_WIDTH` DECIMAL(18,6) NULL COMMENT '宽度',
    MODIFY COLUMN `F_COIL_WEIGHT` DECIMAL(18,6) NULL COMMENT '四米带材重量',
    MODIFY COLUMN `F_SINGLE_COIL_WEIGHT` DECIMAL(18,6) NULL COMMENT '单卷重量(kg)';

-- 3.3 带厚分布 (F_THICK_1 到 F_THICK_22)
ALTER TABLE `LAB_INTERMEDIATE_DATA` 
    MODIFY COLUMN `F_THICK_1` DECIMAL(18,6) NULL COMMENT '带厚1 (μm)',
    MODIFY COLUMN `F_THICK_2` DECIMAL(18,6) NULL COMMENT '带厚2',
    MODIFY COLUMN `F_THICK_3` DECIMAL(18,6) NULL COMMENT '带厚3',
    MODIFY COLUMN `F_THICK_4` DECIMAL(18,6) NULL COMMENT '带厚4',
    MODIFY COLUMN `F_THICK_5` DECIMAL(18,6) NULL COMMENT '带厚5',
    MODIFY COLUMN `F_THICK_6` DECIMAL(18,6) NULL COMMENT '带厚6',
    MODIFY COLUMN `F_THICK_7` DECIMAL(18,6) NULL COMMENT '带厚7',
    MODIFY COLUMN `F_THICK_8` DECIMAL(18,6) NULL COMMENT '带厚8',
    MODIFY COLUMN `F_THICK_9` DECIMAL(18,6) NULL COMMENT '带厚9',
    MODIFY COLUMN `F_THICK_10` DECIMAL(18,6) NULL COMMENT '带厚10',
    MODIFY COLUMN `F_THICK_11` DECIMAL(18,6) NULL COMMENT '带厚11',
    MODIFY COLUMN `F_THICK_12` DECIMAL(18,6) NULL COMMENT '带厚12',
    MODIFY COLUMN `F_THICK_13` DECIMAL(18,6) NULL COMMENT '带厚13',
    MODIFY COLUMN `F_THICK_14` DECIMAL(18,6) NULL COMMENT '带厚14',
    MODIFY COLUMN `F_THICK_15` DECIMAL(18,6) NULL COMMENT '带厚15',
    MODIFY COLUMN `F_THICK_16` DECIMAL(18,6) NULL COMMENT '带厚16',
    MODIFY COLUMN `F_THICK_17` DECIMAL(18,6) NULL COMMENT '带厚17',
    MODIFY COLUMN `F_THICK_18` DECIMAL(18,6) NULL COMMENT '带厚18',
    MODIFY COLUMN `F_THICK_19` DECIMAL(18,6) NULL COMMENT '带厚19',
    MODIFY COLUMN `F_THICK_20` DECIMAL(18,6) NULL COMMENT '带厚20',
    MODIFY COLUMN `F_THICK_21` DECIMAL(18,6) NULL COMMENT '带厚21',
    MODIFY COLUMN `F_THICK_22` DECIMAL(18,6) NULL COMMENT '带厚22';

-- 3.4 带厚范围和汇总
ALTER TABLE `LAB_INTERMEDIATE_DATA` 
    MODIFY COLUMN `F_THICK_MIN` DECIMAL(18,6) NULL COMMENT '带厚最小值',
    MODIFY COLUMN `F_THICK_MAX` DECIMAL(18,6) NULL COMMENT '带厚最大值',
    MODIFY COLUMN `F_THICK_DIFF` DECIMAL(18,6) NULL COMMENT '带厚极差';

-- 3.5 产品规格参数
ALTER TABLE `LAB_INTERMEDIATE_DATA` 
    MODIFY COLUMN `F_PRODUCT_LENGTH` DECIMAL(18,6) NULL COMMENT '产品长度',
    MODIFY COLUMN `F_PRODUCT_DENSITY` DECIMAL(18,6) NULL COMMENT '产品密度';

-- 3.6 计算字段
ALTER TABLE `LAB_INTERMEDIATE_DATA` 
    MODIFY COLUMN `F_DENSITY` DECIMAL(18,6) NULL COMMENT '密度 (g/cm³)',
    MODIFY COLUMN `F_LAM_FACTOR` DECIMAL(18,6) NULL COMMENT '叠片系数 (%)';

-- 3.7 花纹数据
ALTER TABLE `LAB_INTERMEDIATE_DATA` 
    MODIFY COLUMN `F_L_PATTERN_W` DECIMAL(18,6) NULL COMMENT '左花纹纹宽',
    MODIFY COLUMN `F_L_PATTERN_S` DECIMAL(18,6) NULL COMMENT '左花纹纹间距',
    MODIFY COLUMN `F_M_PATTERN_W` DECIMAL(18,6) NULL COMMENT '中花纹纹宽',
    MODIFY COLUMN `F_M_PATTERN_S` DECIMAL(18,6) NULL COMMENT '中花纹纹间距',
    MODIFY COLUMN `F_R_PATTERN_W` DECIMAL(18,6) NULL COMMENT '右花纹纹宽',
    MODIFY COLUMN `F_R_PATTERN_S` DECIMAL(18,6) NULL COMMENT '右花纹纹间距';

-- 3.8 厚度相关
ALTER TABLE `LAB_INTERMEDIATE_DATA` 
    MODIFY COLUMN `F_AVG_THICKNESS` DECIMAL(18,6) NULL COMMENT '平均厚度 (μm)',
    MODIFY COLUMN `F_MAX_THICKNESS_RAW` DECIMAL(18,6) NULL COMMENT '最大厚度（检测列最大值）',
    MODIFY COLUMN `F_MAX_AVG_THICKNESS` DECIMAL(18,6) NULL COMMENT '最大平均厚度（最大值/层数）',
    MODIFY COLUMN `F_STRIP_TYPE` DECIMAL(18,6) NULL COMMENT '带型';

-- 3.9 叠片系数厚度分布 (F_DETECTION_1 到 F_DETECTION_22)
ALTER TABLE `LAB_INTERMEDIATE_DATA` 
    MODIFY COLUMN `F_DETECTION_1` DECIMAL(18,6) NULL COMMENT '检测数据列1',
    MODIFY COLUMN `F_DETECTION_2` DECIMAL(18,6) NULL COMMENT '检测数据列2',
    MODIFY COLUMN `F_DETECTION_3` DECIMAL(18,6) NULL COMMENT '检测数据列3',
    MODIFY COLUMN `F_DETECTION_4` DECIMAL(18,6) NULL COMMENT '检测数据列4',
    MODIFY COLUMN `F_DETECTION_5` DECIMAL(18,6) NULL COMMENT '检测数据列5',
    MODIFY COLUMN `F_DETECTION_6` DECIMAL(18,6) NULL COMMENT '检测数据列6',
    MODIFY COLUMN `F_DETECTION_7` DECIMAL(18,6) NULL COMMENT '检测数据列7',
    MODIFY COLUMN `F_DETECTION_8` DECIMAL(18,6) NULL COMMENT '检测数据列8',
    MODIFY COLUMN `F_DETECTION_9` DECIMAL(18,6) NULL COMMENT '检测数据列9',
    MODIFY COLUMN `F_DETECTION_10` DECIMAL(18,6) NULL COMMENT '检测数据列10',
    MODIFY COLUMN `F_DETECTION_11` DECIMAL(18,6) NULL COMMENT '检测数据列11',
    MODIFY COLUMN `F_DETECTION_12` DECIMAL(18,6) NULL COMMENT '检测数据列12',
    MODIFY COLUMN `F_DETECTION_13` DECIMAL(18,6) NULL COMMENT '检测数据列13',
    MODIFY COLUMN `F_DETECTION_14` DECIMAL(18,6) NULL COMMENT '检测数据列14',
    MODIFY COLUMN `F_DETECTION_15` DECIMAL(18,6) NULL COMMENT '检测数据列15',
    MODIFY COLUMN `F_DETECTION_16` DECIMAL(18,6) NULL COMMENT '检测数据列16',
    MODIFY COLUMN `F_DETECTION_17` DECIMAL(18,6) NULL COMMENT '检测数据列17',
    MODIFY COLUMN `F_DETECTION_18` DECIMAL(18,6) NULL COMMENT '检测数据列18',
    MODIFY COLUMN `F_DETECTION_19` DECIMAL(18,6) NULL COMMENT '检测数据列19',
    MODIFY COLUMN `F_DETECTION_20` DECIMAL(18,6) NULL COMMENT '检测数据列20',
    MODIFY COLUMN `F_DETECTION_21` DECIMAL(18,6) NULL COMMENT '检测数据列21',
    MODIFY COLUMN `F_DETECTION_22` DECIMAL(18,6) NULL COMMENT '检测数据列22';

-- =============================================
-- 执行完成
-- =============================================
