DROP TABLE IF EXISTS `LAB_RAW_DATA`;

CREATE TABLE `LAB_RAW_DATA` (
  `F_Id` varchar(50) NOT NULL COMMENT '主键',
  `F_PROD_DATE` datetime DEFAULT NULL COMMENT '生产日期',
  `F_FURNACE_NO` varchar(100) DEFAULT NULL COMMENT '原始炉号',
  `F_LINE_NO` int DEFAULT NULL COMMENT '产线',
  `F_SHIFT` varchar(10) DEFAULT NULL COMMENT '班次',
  `F_SHIFT_NUMERIC` int DEFAULT NULL COMMENT '班次数字',
  `F_FURNACE_NO_PARSED` int DEFAULT NULL COMMENT '炉号',
  `F_COIL_NO` int DEFAULT NULL COMMENT '卷号',
  `F_SUBCOIL_NO` int DEFAULT NULL COMMENT '分卷号',
  `F_FEATURE_SUFFIX` varchar(50) DEFAULT NULL COMMENT '特性描述',
  `F_WIDTH` decimal(18,2) DEFAULT NULL COMMENT '宽度',
  `F_COIL_WEIGHT` decimal(18,2) DEFAULT NULL COMMENT '带材重量',
  `F_PRODUCT_SPEC_ID` varchar(50) DEFAULT NULL COMMENT '产品规格ID',
  `F_PRODUCT_SPEC_CODE` varchar(50) DEFAULT NULL COMMENT '产品规格代码',
  `F_PRODUCT_SPEC_NAME` varchar(100) DEFAULT NULL COMMENT '产品规格名称',
  `F_PRODUCT_SPEC_VERSION` varchar(50) DEFAULT NULL COMMENT '产品规格版本',
  `F_DETECTION_COLUMNS` varchar(100) DEFAULT NULL COMMENT '检测列',
  `F_DETECTION_DATA` json DEFAULT NULL COMMENT '检测数据列',
  `F_IS_VALID_DATA` int DEFAULT '0' COMMENT '有效数据标识',
  `F_SOURCE_FILE_ID` varchar(50) DEFAULT NULL COMMENT 'Excel源文件ID',
  `F_IMPORT_SESSION_ID` varchar(50) DEFAULT NULL COMMENT '导入会话ID',
  `F_APPEARANCE_FEATURE_IDS` json DEFAULT NULL COMMENT '匹配后的特性ID列表',
  `F_IMPORT_ERROR` varchar(500) DEFAULT NULL COMMENT '导入错误信息',
  `F_IMPORT_STATUS` int NOT NULL DEFAULT '0' COMMENT '导入状态',
  `F_SORTCODE` bigint DEFAULT NULL COMMENT '排序码',
  
  -- Common fields
  `F_CREATORTIME` datetime DEFAULT NULL COMMENT '创建时间',
  `F_CREATORUSERID` varchar(50) DEFAULT NULL COMMENT '创建用户',
  `F_ENABLEDMARK` int DEFAULT NULL COMMENT '启用标识',
  `F_LastModifyTime` datetime DEFAULT NULL COMMENT '修改时间',
  `F_LastModifyUserId` varchar(50) DEFAULT NULL COMMENT '修改用户',
  `F_DeleteMark` int DEFAULT NULL COMMENT '删除标志',
  `F_DeleteTime` datetime DEFAULT NULL COMMENT '删除时间',
  `F_DeleteUserId` varchar(50) DEFAULT NULL COMMENT '删除用户',
  `F_TenantId` varchar(50) DEFAULT NULL COMMENT '租户ID',
  
  PRIMARY KEY (`F_Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='原始数据';
