-- ============================================
-- 外观特性模块 - 完整表创建脚本
-- 说明: 
--   1. 特性大类和特性等级使用ID作为外键
--   2. 前端展示时通过关联查询获取名称
--   3. 唯一性约束：特征大类ID + 特性名称 + 特性等级ID 组合唯一
-- 创建时间: 2026-01-11
-- ============================================

-- ============================================
-- MySQL版本（推荐）
-- ============================================

-- ============================================
-- 1. 外观特性大类表 (LAB_APPEARANCE_FEATURE_CATEGORY)
-- ============================================
DROP TABLE IF EXISTS `LAB_APPEARANCE_FEATURE_CATEGORY`;

CREATE TABLE `LAB_APPEARANCE_FEATURE_CATEGORY` (
    `F_Id` VARCHAR(50) NOT NULL COMMENT '主键ID',
    `F_NAME` VARCHAR(100) NOT NULL COMMENT '大类名称',
    `F_DESCRIPTION` VARCHAR(500) NULL COMMENT '大类描述',
    `F_SORTCODE` BIGINT NULL COMMENT '排序码',
    `F_PARENTID` VARCHAR(50) NULL COMMENT '父级分类ID',
    `F_CREATORUSERID` VARCHAR(50) NULL COMMENT '创建人ID',
    `F_CREATORTIME` DATETIME NULL COMMENT '创建时间',
    `F_LastModifyUserId` VARCHAR(50) NULL COMMENT '最后修改人ID',
    `F_LastModifyTime` DATETIME NULL COMMENT '最后修改时间',
    `F_DeleteMark` INT NULL COMMENT '删除标记',
    `F_DeleteTime` DATETIME NULL COMMENT '删除时间',
    `F_DeleteUserId` VARCHAR(50) NULL COMMENT '删除人ID',
    `F_ENABLEDMARK` INT NULL DEFAULT 1 COMMENT '启用标识',
    `F_TenantId` VARCHAR(50) NULL COMMENT '租户ID',
    PRIMARY KEY (`F_Id`),
    INDEX `IDX_NAME` (`F_NAME`),
    INDEX `IDX_PARENTID` (`F_PARENTID`),
    INDEX `IDX_DELETEMARK` (`F_DeleteMark`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='外观特性大类表';

-- ============================================
-- 2. 外观特性等级表 (LAB_APPEARANCE_FEATURE_LEVEL)
-- ============================================
DROP TABLE IF EXISTS `LAB_APPEARANCE_FEATURE_LEVEL`;

CREATE TABLE `LAB_APPEARANCE_FEATURE_LEVEL` (
    `F_Id` VARCHAR(50) NOT NULL COMMENT '主键ID',
    `F_NAME` VARCHAR(50) NOT NULL COMMENT '等级名称',
    `F_DESCRIPTION` VARCHAR(200) NULL COMMENT '等级描述',
    `F_SORTCODE` BIGINT NULL COMMENT '排序码',
    `F_ENABLED` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    `F_ISDEFAULT` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否默认',
    `F_CREATORUSERID` VARCHAR(50) NULL COMMENT '创建人ID',
    `F_CREATORTIME` DATETIME NULL COMMENT '创建时间',
    `F_LastModifyUserId` VARCHAR(50) NULL COMMENT '最后修改人ID',
    `F_LastModifyTime` DATETIME NULL COMMENT '最后修改时间',
    `F_DeleteMark` INT NULL COMMENT '删除标记',
    `F_DeleteTime` DATETIME NULL COMMENT '删除时间',
    `F_DeleteUserId` VARCHAR(50) NULL COMMENT '删除人ID',
    `F_ENABLEDMARK` INT NULL DEFAULT 1 COMMENT '启用标识',
    `F_TenantId` VARCHAR(50) NULL COMMENT '租户ID',
    PRIMARY KEY (`F_Id`),
    UNIQUE KEY `UK_NAME` (`F_NAME`, `F_DeleteMark`),
    INDEX `IDX_ENABLED` (`F_ENABLED`),
    INDEX `IDX_ISDEFAULT` (`F_ISDEFAULT`),
    INDEX `IDX_DELETEMARK` (`F_DeleteMark`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='外观特性等级表';

-- ============================================
-- 3. 外观特性定义表 (LAB_APPEARANCE_FEATURE)
-- ============================================
DROP TABLE IF EXISTS `LAB_APPEARANCE_FEATURE`;

CREATE TABLE `LAB_APPEARANCE_FEATURE` (
    `F_Id` VARCHAR(50) NOT NULL COMMENT '主键ID',
    `F_CATEGORY_ID` VARCHAR(50) NOT NULL COMMENT '特性大类ID',
    `F_NAME` VARCHAR(100) NOT NULL COMMENT '特性名称',
    `F_SEVERITY_LEVEL_ID` VARCHAR(50) NOT NULL COMMENT '特性等级ID',
    `F_KEYWORDS` VARCHAR(1000) NULL COMMENT '关键字列表（JSON数组）',
    `F_DESCRIPTION` VARCHAR(500) NULL COMMENT '描述',
    `F_SORTCODE` BIGINT NULL COMMENT '排序码',
    `F_CREATORUSERID` VARCHAR(50) NULL COMMENT '创建人ID',
    `F_CREATORTIME` DATETIME NULL COMMENT '创建时间',
    `F_LastModifyUserId` VARCHAR(50) NULL COMMENT '最后修改人ID',
    `F_LastModifyTime` DATETIME NULL COMMENT '最后修改时间',
    `F_DeleteMark` INT NULL COMMENT '删除标记',
    `F_DeleteTime` DATETIME NULL COMMENT '删除时间',
    `F_DeleteUserId` VARCHAR(50) NULL COMMENT '删除人ID',
    `F_ENABLEDMARK` INT NULL DEFAULT 1 COMMENT '启用标识',
    `F_TenantId` VARCHAR(50) NULL COMMENT '租户ID',
    PRIMARY KEY (`F_Id`),
    UNIQUE KEY `UK_CATEGORY_ID_NAME_SEVERITY_ID` (`F_CATEGORY_ID`, `F_NAME`, `F_SEVERITY_LEVEL_ID`),
    INDEX `IDX_CATEGORY_ID` (`F_CATEGORY_ID`),
    INDEX `IDX_SEVERITY_LEVEL_ID` (`F_SEVERITY_LEVEL_ID`),
    INDEX `IDX_NAME` (`F_NAME`),
    INDEX `IDX_DELETEMARK` (`F_DeleteMark`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='外观特性定义表';

-- ============================================
-- 4. 外观特性人工修正记录表 (LAB_APPEARANCE_FEATURE_CORRECTION)
-- ============================================
DROP TABLE IF EXISTS `LAB_APPEARANCE_FEATURE_CORRECTION`;

CREATE TABLE `LAB_APPEARANCE_FEATURE_CORRECTION` (
    `F_Id` VARCHAR(50) NOT NULL COMMENT '主键ID',
    `F_INPUT_TEXT` VARCHAR(500) NOT NULL COMMENT '原始输入文本',
    `F_AUTO_MATCHED_FEATURE_ID` VARCHAR(50) NULL COMMENT '自动匹配的特征ID',
    `F_CORRECTED_FEATURE_ID` VARCHAR(50) NOT NULL COMMENT '人工修正后的特征ID',
    `F_MATCH_MODE` VARCHAR(20) NOT NULL COMMENT '匹配模式',
    `F_SCENARIO` VARCHAR(20) NOT NULL COMMENT '使用场景',
    `F_REMARK` VARCHAR(500) NULL COMMENT '备注',
    `F_CREATORUSERID` VARCHAR(50) NULL COMMENT '创建人ID',
    `F_CREATORTIME` DATETIME NULL COMMENT '创建时间',
    `F_LastModifyUserId` VARCHAR(50) NULL COMMENT '最后修改人ID',
    `F_LastModifyTime` DATETIME NULL COMMENT '最后修改时间',
    `F_DeleteMark` INT NULL COMMENT '删除标记',
    `F_DeleteTime` DATETIME NULL COMMENT '删除时间',
    `F_DeleteUserId` VARCHAR(50) NULL COMMENT '删除人ID',
    `F_ENABLEDMARK` INT NULL DEFAULT 1 COMMENT '启用标识',
    `F_TenantId` VARCHAR(50) NULL COMMENT '租户ID',
    PRIMARY KEY (`F_Id`),
    INDEX `IDX_INPUT_TEXT` (`F_INPUT_TEXT`),
    INDEX `IDX_AUTO_MATCHED_FEATURE_ID` (`F_AUTO_MATCHED_FEATURE_ID`),
    INDEX `IDX_CORRECTED_FEATURE_ID` (`F_CORRECTED_FEATURE_ID`),
    INDEX `IDX_MATCH_MODE` (`F_MATCH_MODE`),
    INDEX `IDX_SCENARIO` (`F_SCENARIO`),
    INDEX `IDX_DELETEMARK` (`F_DeleteMark`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='外观特性人工修正记录表';

-- ============================================
-- SQL Server版本（备用）
-- ============================================
/*
-- ============================================
-- 1. 外观特性大类表 (LAB_APPEARANCE_FEATURE_CATEGORY)
-- ============================================
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'LAB_APPEARANCE_FEATURE_CATEGORY') AND type in (N'U'))
BEGIN
    DROP TABLE LAB_APPEARANCE_FEATURE_CATEGORY;
END
GO

CREATE TABLE LAB_APPEARANCE_FEATURE_CATEGORY (
    F_Id NVARCHAR(50) NOT NULL,
    F_NAME NVARCHAR(100) NOT NULL,
    F_DESCRIPTION NVARCHAR(500) NULL,
    F_SORTCODE BIGINT NULL,
    F_PARENTID NVARCHAR(50) NULL,
    F_CREATORUSERID NVARCHAR(50) NULL,
    F_CREATORTIME DATETIME NULL,
    F_LastModifyUserId NVARCHAR(50) NULL,
    F_LastModifyTime DATETIME NULL,
    F_DeleteMark INT NULL,
    F_DeleteTime DATETIME NULL,
    F_DeleteUserId NVARCHAR(50) NULL,
    F_ENABLEDMARK INT NULL DEFAULT 1,
    F_TenantId NVARCHAR(50) NULL,
    PRIMARY KEY (F_Id)
);
GO

CREATE INDEX IDX_NAME ON LAB_APPEARANCE_FEATURE_CATEGORY (F_NAME);
CREATE INDEX IDX_PARENTID ON LAB_APPEARANCE_FEATURE_CATEGORY (F_PARENTID);
CREATE INDEX IDX_DELETEMARK ON LAB_APPEARANCE_FEATURE_CATEGORY (F_DeleteMark);
GO

-- ============================================
-- 2. 外观特性等级表 (LAB_APPEARANCE_FEATURE_LEVEL)
-- ============================================
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'LAB_APPEARANCE_FEATURE_LEVEL') AND type in (N'U'))
BEGIN
    DROP TABLE LAB_APPEARANCE_FEATURE_LEVEL;
END
GO

CREATE TABLE LAB_APPEARANCE_FEATURE_LEVEL (
    F_Id NVARCHAR(50) NOT NULL,
    F_NAME NVARCHAR(50) NOT NULL,
    F_DESCRIPTION NVARCHAR(200) NULL,
    F_SORTCODE BIGINT NULL,
    F_ENABLED BIT NOT NULL DEFAULT 1,
    F_ISDEFAULT BIT NOT NULL DEFAULT 0,
    F_CREATORUSERID NVARCHAR(50) NULL,
    F_CREATORTIME DATETIME NULL,
    F_LastModifyUserId NVARCHAR(50) NULL,
    F_LastModifyTime DATETIME NULL,
    F_DeleteMark INT NULL,
    F_DeleteTime DATETIME NULL,
    F_DeleteUserId NVARCHAR(50) NULL,
    F_ENABLEDMARK INT NULL DEFAULT 1,
    F_TenantId NVARCHAR(50) NULL,
    PRIMARY KEY (F_Id)
);
GO

CREATE UNIQUE INDEX UK_NAME ON LAB_APPEARANCE_FEATURE_LEVEL (F_NAME, F_DeleteMark);
CREATE INDEX IDX_ENABLED ON LAB_APPEARANCE_FEATURE_LEVEL (F_ENABLED);
CREATE INDEX IDX_ISDEFAULT ON LAB_APPEARANCE_FEATURE_LEVEL (F_ISDEFAULT);
CREATE INDEX IDX_DELETEMARK ON LAB_APPEARANCE_FEATURE_LEVEL (F_DeleteMark);
GO

-- ============================================
-- 3. 外观特性定义表 (LAB_APPEARANCE_FEATURE)
-- ============================================
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'LAB_APPEARANCE_FEATURE') AND type in (N'U'))
BEGIN
    DROP TABLE LAB_APPEARANCE_FEATURE;
END
GO

CREATE TABLE LAB_APPEARANCE_FEATURE (
    F_Id NVARCHAR(50) NOT NULL,
    F_CATEGORY_ID NVARCHAR(50) NOT NULL,
    F_NAME NVARCHAR(100) NOT NULL,
    F_SEVERITY_LEVEL_ID NVARCHAR(50) NOT NULL,
    F_KEYWORDS NVARCHAR(1000) NULL,
    F_DESCRIPTION NVARCHAR(500) NULL,
    F_SORTCODE BIGINT NULL,
    F_CREATORUSERID NVARCHAR(50) NULL,
    F_CREATORTIME DATETIME NULL,
    F_LastModifyUserId NVARCHAR(50) NULL,
    F_LastModifyTime DATETIME NULL,
    F_DeleteMark INT NULL,
    F_DeleteTime DATETIME NULL,
    F_DeleteUserId NVARCHAR(50) NULL,
    F_ENABLEDMARK INT NULL DEFAULT 1,
    F_TenantId NVARCHAR(50) NULL,
    PRIMARY KEY (F_Id)
);
GO

CREATE UNIQUE INDEX UK_CATEGORY_ID_NAME_SEVERITY_ID ON LAB_APPEARANCE_FEATURE (F_CATEGORY_ID, F_NAME, F_SEVERITY_LEVEL_ID);
CREATE INDEX IDX_CATEGORY_ID ON LAB_APPEARANCE_FEATURE (F_CATEGORY_ID);
CREATE INDEX IDX_SEVERITY_LEVEL_ID ON LAB_APPEARANCE_FEATURE (F_SEVERITY_LEVEL_ID);
CREATE INDEX IDX_NAME ON LAB_APPEARANCE_FEATURE (F_NAME);
CREATE INDEX IDX_DELETEMARK ON LAB_APPEARANCE_FEATURE (F_DeleteMark);
GO

-- ============================================
-- 4. 外观特性人工修正记录表 (LAB_APPEARANCE_FEATURE_CORRECTION)
-- ============================================
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'LAB_APPEARANCE_FEATURE_CORRECTION') AND type in (N'U'))
BEGIN
    DROP TABLE LAB_APPEARANCE_FEATURE_CORRECTION;
END
GO

CREATE TABLE LAB_APPEARANCE_FEATURE_CORRECTION (
    F_Id NVARCHAR(50) NOT NULL,
    F_INPUT_TEXT NVARCHAR(500) NOT NULL,
    F_AUTO_MATCHED_FEATURE_ID NVARCHAR(50) NULL,
    F_CORRECTED_FEATURE_ID NVARCHAR(50) NOT NULL,
    F_MATCH_MODE NVARCHAR(20) NOT NULL,
    F_SCENARIO NVARCHAR(20) NOT NULL,
    F_REMARK NVARCHAR(500) NULL,
    F_CREATORUSERID NVARCHAR(50) NULL,
    F_CREATORTIME DATETIME NULL,
    F_LastModifyUserId NVARCHAR(50) NULL,
    F_LastModifyTime DATETIME NULL,
    F_DeleteMark INT NULL,
    F_DeleteTime DATETIME NULL,
    F_DeleteUserId NVARCHAR(50) NULL,
    F_ENABLEDMARK INT NULL DEFAULT 1,
    F_TenantId NVARCHAR(50) NULL,
    PRIMARY KEY (F_Id)
);
GO

CREATE INDEX IDX_INPUT_TEXT ON LAB_APPEARANCE_FEATURE_CORRECTION (F_INPUT_TEXT);
CREATE INDEX IDX_AUTO_MATCHED_FEATURE_ID ON LAB_APPEARANCE_FEATURE_CORRECTION (F_AUTO_MATCHED_FEATURE_ID);
CREATE INDEX IDX_CORRECTED_FEATURE_ID ON LAB_APPEARANCE_FEATURE_CORRECTION (F_CORRECTED_FEATURE_ID);
CREATE INDEX IDX_MATCH_MODE ON LAB_APPEARANCE_FEATURE_CORRECTION (F_MATCH_MODE);
CREATE INDEX IDX_SCENARIO ON LAB_APPEARANCE_FEATURE_CORRECTION (F_SCENARIO);
CREATE INDEX IDX_DELETEMARK ON LAB_APPEARANCE_FEATURE_CORRECTION (F_DeleteMark);
GO
*/

-- ============================================
-- 说明
-- ============================================
-- 1. 所有表都包含基础字段（继承自CLDEntityBase）
-- 2. 特性大类和特性等级使用ID作为外键，前端展示时通过关联查询获取名称
-- 3. 唯一性约束：特征大类ID + 特性名称 + 特性等级ID 组合唯一
-- 4. 支持软删除机制（通过F_DeleteMark字段）
-- 5. 支持多租户（通过F_TenantId字段）
-- 6. 字段名严格按照CLDEntityBase和OEntityBase中定义的ColumnName：
--    - F_Id (主键，大小写混合)
--    - F_CREATORTIME, F_CREATORUSERID, F_ENABLEDMARK (全大写)
--    - F_LastModifyTime, F_LastModifyUserId (大小写混合)
--    - F_DeleteMark, F_DeleteTime, F_DeleteUserId (大小写混合)
--    - F_TenantId (大小写混合)
