-- ============================================
-- 公共维度定义表 - 创建脚本
-- 说明: 
--   1. 存储公共维度定义，用户自定义维度信息，用于计算使用
--   2. 维度信息可以选择单位，精度用于计算时保证计算的精度
--   3. 维度值是必填，不需要默认值
--   4. 支持版本管理，因为跟着技术要求，值会有变动
-- 创建时间: 2025-01-XX
-- ============================================

-- ============================================
-- MySQL版本
-- ============================================

-- 1. 公共维度定义表
CREATE TABLE IF NOT EXISTS `LAB_PUBLIC_DIMENSION` (
    `F_Id` VARCHAR(50) NOT NULL COMMENT '主键ID',
    `F_DIMENSION_NAME` VARCHAR(100) NOT NULL COMMENT '维度名称（如：长度、层数、密度）',
    `F_DIMENSION_KEY` VARCHAR(100) NOT NULL COMMENT '维度键名（如：length、layers、density）',
    `F_VALUE_TYPE` VARCHAR(20) NOT NULL COMMENT '维度值类型（decimal、int、text）',
    `F_UNIT_ID` VARCHAR(50) NULL COMMENT '单位ID（关联单位定义表）',
    `F_UNIT` VARCHAR(20) NULL COMMENT '属性单位（如：m、mm、kg、MPa、%），冗余字段便于查询',
    `F_PRECISION` INT NULL COMMENT '精度（仅用于数字类型，小数位数）',
    `F_SORTCODE` BIGINT NULL COMMENT '排序码',
    `F_CREATORUSERID` VARCHAR(50) NULL COMMENT '创建人ID',
    `F_CREATORTIME` DATETIME NULL COMMENT '创建时间',
    `F_LastModifyUserId` VARCHAR(50) NULL COMMENT '最后修改人ID',
    `F_LastModifyTime` DATETIME NULL COMMENT '最后修改时间',
    `F_DeleteMark` INT NULL COMMENT '删除标记',
    `F_DeleteTime` DATETIME NULL COMMENT '删除时间',
    `F_DeleteUserId` VARCHAR(50) NULL COMMENT '删除人ID',
    `F_TenantId` VARCHAR(50) NULL COMMENT '租户ID',
    PRIMARY KEY (`F_Id`),
    INDEX `IDX_DIMENSION_KEY` (`F_DIMENSION_KEY`),
    INDEX `IDX_DELETEMARK` (`F_DeleteMark`),
    INDEX `IDX_UNIT_ID` (`F_UNIT_ID`),
    UNIQUE KEY `UK_DIMENSION_KEY` (`F_DIMENSION_KEY`, `F_DeleteMark`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='公共维度定义表';

-- 2. 公共维度版本表
CREATE TABLE IF NOT EXISTS `LAB_PUBLIC_DIMENSION_VERSION` (
    `F_ID` VARCHAR(50) NOT NULL COMMENT '主键',
    `F_TENANTID` VARCHAR(50) DEFAULT NULL COMMENT '租户ID',
    `F_DIMENSION_ID` VARCHAR(50) NOT NULL COMMENT '公共维度ID',
    `F_VERSION` INT NOT NULL DEFAULT '1' COMMENT '版本号',
    `F_VERSION_NAME` VARCHAR(100) DEFAULT NULL COMMENT '版本名称',
    `F_VERSION_DESCRIPTION` VARCHAR(500) DEFAULT NULL COMMENT '版本说明',
    `F_IS_CURRENT` INT NOT NULL DEFAULT '0' COMMENT '是否当前版本（1=是，0=否）',
    `F_CREATOR_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
    `F_CREATOR_USER_ID` VARCHAR(50) DEFAULT NULL COMMENT '创建人ID',
    `F_LAST_MODIFY_TIME` DATETIME DEFAULT NULL COMMENT '最后修改时间',
    `F_LAST_MODIFY_USER_ID` VARCHAR(50) DEFAULT NULL COMMENT '最后修改人ID',
    `F_DELETE_MARK` INT DEFAULT '0' COMMENT '删除标记',
    `F_DELETE_TIME` DATETIME DEFAULT NULL COMMENT '删除时间',
    `F_DELETE_USER_ID` VARCHAR(50) DEFAULT NULL COMMENT '删除人ID',
    PRIMARY KEY (`F_ID`),
    KEY `IX_DIMENSION_VERSION_DIMENSION_ID` (`F_DIMENSION_ID`),
    KEY `IX_DIMENSION_VERSION_IS_CURRENT` (`F_IS_CURRENT`),
    KEY `IX_DIMENSION_VERSION_DELETE_MARK` (`F_DELETE_MARK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='公共维度版本快照表';

-- ============================================
-- SQL Server版本
-- ============================================

/*
-- 1. 公共维度定义表
CREATE TABLE [LAB_PUBLIC_DIMENSION] (
    [F_Id] VARCHAR(50) NOT NULL PRIMARY KEY,
    [F_DIMENSION_NAME] NVARCHAR(100) NOT NULL,
    [F_DIMENSION_KEY] VARCHAR(100) NOT NULL,
    [F_VALUE_TYPE] VARCHAR(20) NOT NULL,
    [F_UNIT_ID] VARCHAR(50) NULL,
    [F_UNIT] VARCHAR(20) NULL,
    [F_PRECISION] INT NULL,
    [F_SORTCODE] BIGINT NULL,
    [F_CREATORUSERID] VARCHAR(50) NULL,
    [F_CREATORTIME] DATETIME NULL,
    [F_LastModifyUserId] VARCHAR(50) NULL,
    [F_LastModifyTime] DATETIME NULL,
    [F_DeleteMark] INT NULL,
    [F_DeleteTime] DATETIME NULL,
    [F_DeleteUserId] VARCHAR(50) NULL,
    [F_TenantId] VARCHAR(50) NULL,
    CONSTRAINT [UK_DIMENSION_KEY] UNIQUE ([F_DIMENSION_KEY], [F_DeleteMark])
);

CREATE INDEX [IDX_DIMENSION_KEY] ON [LAB_PUBLIC_DIMENSION] ([F_DIMENSION_KEY]);
CREATE INDEX [IDX_DELETEMARK] ON [LAB_PUBLIC_DIMENSION] ([F_DeleteMark]);
CREATE INDEX [IDX_UNIT_ID] ON [LAB_PUBLIC_DIMENSION] ([F_UNIT_ID]);

-- 2. 公共维度版本表
CREATE TABLE [LAB_PUBLIC_DIMENSION_VERSION] (
    [F_ID] VARCHAR(50) NOT NULL PRIMARY KEY,
    [F_TENANTID] VARCHAR(50) DEFAULT NULL,
    [F_DIMENSION_ID] VARCHAR(50) NOT NULL,
    [F_VERSION] INT NOT NULL DEFAULT 1,
    [F_VERSION_NAME] NVARCHAR(100) DEFAULT NULL,
    [F_VERSION_DESCRIPTION] NVARCHAR(500) DEFAULT NULL,
    [F_IS_CURRENT] INT NOT NULL DEFAULT 0,
    [F_CREATOR_TIME] DATETIME DEFAULT NULL,
    [F_CREATOR_USER_ID] VARCHAR(50) DEFAULT NULL,
    [F_LAST_MODIFY_TIME] DATETIME DEFAULT NULL,
    [F_LAST_MODIFY_USER_ID] VARCHAR(50) DEFAULT NULL,
    [F_DELETE_MARK] INT DEFAULT 0,
    [F_DELETE_TIME] DATETIME DEFAULT NULL,
    [F_DELETE_USER_ID] VARCHAR(50) DEFAULT NULL
);

CREATE INDEX [IX_DIMENSION_VERSION_DIMENSION_ID] ON [LAB_PUBLIC_DIMENSION_VERSION] ([F_DIMENSION_ID]);
CREATE INDEX [IX_DIMENSION_VERSION_IS_CURRENT] ON [LAB_PUBLIC_DIMENSION_VERSION] ([F_IS_CURRENT]);
CREATE INDEX [IX_DIMENSION_VERSION_DELETE_MARK] ON [LAB_PUBLIC_DIMENSION_VERSION] ([F_DELETE_MARK]);
*/

-- ============================================
-- PostgreSQL版本
-- ============================================

/*
-- 1. 公共维度定义表
CREATE TABLE IF NOT EXISTS "LAB_PUBLIC_DIMENSION" (
    "F_Id" VARCHAR(50) NOT NULL PRIMARY KEY,
    "F_DIMENSION_NAME" VARCHAR(100) NOT NULL,
    "F_DIMENSION_KEY" VARCHAR(100) NOT NULL,
    "F_VALUE_TYPE" VARCHAR(20) NOT NULL,
    "F_UNIT_ID" VARCHAR(50) NULL,
    "F_UNIT" VARCHAR(20) NULL,
    "F_PRECISION" INT NULL,
    "F_SORTCODE" BIGINT NULL,
    "F_CREATORUSERID" VARCHAR(50) NULL,
    "F_CREATORTIME" TIMESTAMP NULL,
    "F_LastModifyUserId" VARCHAR(50) NULL,
    "F_LastModifyTime" TIMESTAMP NULL,
    "F_DeleteMark" INT NULL,
    "F_DeleteTime" TIMESTAMP NULL,
    "F_DeleteUserId" VARCHAR(50) NULL,
    "F_TenantId" VARCHAR(50) NULL,
    CONSTRAINT "UK_DIMENSION_KEY" UNIQUE ("F_DIMENSION_KEY", "F_DeleteMark")
);

CREATE INDEX "IDX_DIMENSION_KEY" ON "LAB_PUBLIC_DIMENSION" ("F_DIMENSION_KEY");
CREATE INDEX "IDX_DELETEMARK" ON "LAB_PUBLIC_DIMENSION" ("F_DeleteMark");
CREATE INDEX "IDX_UNIT_ID" ON "LAB_PUBLIC_DIMENSION" ("F_UNIT_ID");

-- 2. 公共维度版本表
CREATE TABLE IF NOT EXISTS "LAB_PUBLIC_DIMENSION_VERSION" (
    "F_ID" VARCHAR(50) NOT NULL PRIMARY KEY,
    "F_TENANTID" VARCHAR(50) DEFAULT NULL,
    "F_DIMENSION_ID" VARCHAR(50) NOT NULL,
    "F_VERSION" INT NOT NULL DEFAULT 1,
    "F_VERSION_NAME" VARCHAR(100) DEFAULT NULL,
    "F_VERSION_DESCRIPTION" VARCHAR(500) DEFAULT NULL,
    "F_IS_CURRENT" INT NOT NULL DEFAULT 0,
    "F_CREATOR_TIME" TIMESTAMP DEFAULT NULL,
    "F_CREATOR_USER_ID" VARCHAR(50) DEFAULT NULL,
    "F_LAST_MODIFY_TIME" TIMESTAMP DEFAULT NULL,
    "F_LAST_MODIFY_USER_ID" VARCHAR(50) DEFAULT NULL,
    "F_DELETE_MARK" INT DEFAULT 0,
    "F_DELETE_TIME" TIMESTAMP DEFAULT NULL,
    "F_DELETE_USER_ID" VARCHAR(50) DEFAULT NULL
);

CREATE INDEX "IX_DIMENSION_VERSION_DIMENSION_ID" ON "LAB_PUBLIC_DIMENSION_VERSION" ("F_DIMENSION_ID");
CREATE INDEX "IX_DIMENSION_VERSION_IS_CURRENT" ON "LAB_PUBLIC_DIMENSION_VERSION" ("F_IS_CURRENT");
CREATE INDEX "IX_DIMENSION_VERSION_DELETE_MARK" ON "LAB_PUBLIC_DIMENSION_VERSION" ("F_DELETE_MARK");
*/
