-- Add F_FORMULA_TYPE column to LAB_INTERMEDIATE_DATA_FORMULA table
ALTER TABLE `LAB_INTERMEDIATE_DATA_FORMULA` 
ADD COLUMN `F_FORMULA_TYPE` varchar(20) DEFAULT 'CALC' COMMENT '公式类型：CALC-计算公式，JUDGE-判定公式' AFTER `F_FORMULA_LANGUAGE`;

-- Update existing records to default value
UPDATE `LAB_INTERMEDIATE_DATA_FORMULA` SET `F_FORMULA_TYPE` = 'CALC' WHERE `F_FORMULA_TYPE` IS NULL;
