-- ============================================
-- Excel导入模板表 - 创建脚本
-- 说明:
--   1. 存储Excel导入模板配置，用于快速读取和验证导入数据
--   2. 模板关联产品规格，导入时根据产品规格自动匹配模板
--   3. 模板配置以JSON格式存储，包含字段映射、验证规则等
--   4. 支持系统模板（公共）和个人模板（私有）
-- 创建时间: 2026-01-15
-- ============================================

-- ============================================
-- MySQL版本
-- ============================================

-- 1. Excel导入模板表
CREATE TABLE IF NOT EXISTS `LAB_EXCEL_IMPORT_TEMPLATE` (
    `F_Id` VARCHAR(50) NOT NULL COMMENT '主键ID',
    `F_TEMPLATE_NAME` VARCHAR(100) NOT NULL COMMENT '模板名称',
    `F_TEMPLATE_CODE` VARCHAR(50) NOT NULL COMMENT '模板编码（唯一）',
    `F_DESCRIPTION` VARCHAR(500) NULL COMMENT '模板描述',
    `F_TEMPLATE_TYPE` VARCHAR(20) NOT NULL DEFAULT 'system' COMMENT '模板类型：system系统模板/user个人模板',
    `F_OWNER_USER_ID` VARCHAR(50) NULL COMMENT '所有者用户ID（个人模板时有效）',
    `F_CONFIG_JSON` LONGTEXT NULL COMMENT '模板配置（JSON格式）',
    `F_PRODUCT_SPEC_ID` VARCHAR(50) NULL COMMENT '关联的产品规格ID',
    `F_VERSION` INT NOT NULL DEFAULT 1 COMMENT '版本号',
    `F_IS_DEFAULT` INT NOT NULL DEFAULT 0 COMMENT '是否默认模板（0=否，1=是）',
    `F_SORTCODE` BIGINT NULL COMMENT '排序码',
    `F_CREATORUSERID` VARCHAR(50) NULL COMMENT '创建人ID',
    `F_CREATORTIME` DATETIME NULL COMMENT '创建时间',
    `F_LASTMODIFYUSERID` VARCHAR(50) NULL COMMENT '最后修改人ID',
    `F_LASTMODIFYTIME` DATETIME NULL COMMENT '最后修改时间',
    `F_DELETEMARK` INT NULL COMMENT '删除标记（0=未删除，1=已删除）',
    `F_DELETETIME` DATETIME NULL COMMENT '删除时间',
    `F_DELETEUSERID` VARCHAR(50) NULL COMMENT '删除人ID',
    `F_TENANTID` VARCHAR(50) NULL COMMENT '租户ID',
    PRIMARY KEY (`F_Id`),
    UNIQUE KEY `UK_TEMPLATE_CODE` (`F_TEMPLATE_CODE`, `F_DELETEMARK`),
    INDEX `IDX_TEMPLATE_TYPE` (`F_TEMPLATE_TYPE`),
    INDEX `IDX_PRODUCT_SPEC_ID` (`F_PRODUCT_SPEC_ID`),
    INDEX `IDX_IS_DEFAULT` (`F_IS_DEFAULT`),
    INDEX `IDX_DELETEMARK` (`F_DELETEMARK`),
    INDEX `IDX_OWNER_USER_ID` (`F_OWNER_USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Excel导入模板表';

-- ============================================
-- SQL Server版本
-- ============================================

/*
-- 1. Excel导入模板表
CREATE TABLE [LAB_EXCEL_IMPORT_TEMPLATE] (
    [F_Id] VARCHAR(50) NOT NULL PRIMARY KEY,
    [F_TEMPLATE_NAME] NVARCHAR(100) NOT NULL,
    [F_TEMPLATE_CODE] VARCHAR(50) NOT NULL,
    [F_DESCRIPTION] NVARCHAR(500) NULL,
    [F_TEMPLATE_TYPE] VARCHAR(20) NOT NULL DEFAULT 'system',
    [F_OWNER_USER_ID] VARCHAR(50) NULL,
    [F_CONFIG_JSON] NVARCHAR(MAX) NULL,
    [F_PRODUCT_SPEC_ID] VARCHAR(50) NULL,
    [F_VERSION] INT NOT NULL DEFAULT 1,
    [F_IS_DEFAULT] INT NOT NULL DEFAULT 0,
    [F_SORTCODE] BIGINT NULL,
    [F_CREATORUSERID] VARCHAR(50) NULL,
    [F_CREATORTIME] DATETIME NULL,
    [F_LASTMODIFYUSERID] VARCHAR(50) NULL,
    [F_LASTMODIFYTIME] DATETIME NULL,
    [F_DELETEMARK] INT NULL,
    [F_DELETETIME] DATETIME NULL,
    [F_DELETEUSERID] VARCHAR(50) NULL,
    [F_TENANTID] VARCHAR(50) NULL,
    CONSTRAINT [UK_TEMPLATE_CODE] UNIQUE ([F_TEMPLATE_CODE], [F_DELETEMARK])
);

CREATE INDEX [IDX_TEMPLATE_TYPE] ON [LAB_EXCEL_IMPORT_TEMPLATE] ([F_TEMPLATE_TYPE]);
CREATE INDEX [IDX_PRODUCT_SPEC_ID] ON [LAB_EXCEL_IMPORT_TEMPLATE] ([F_PRODUCT_SPEC_ID]);
CREATE INDEX [IDX_IS_DEFAULT] ON [LAB_EXCEL_IMPORT_TEMPLATE] ([F_IS_DEFAULT]);
CREATE INDEX [IDX_DELETEMARK] ON [LAB_EXCEL_IMPORT_TEMPLATE] ([F_DELETEMARK]);
CREATE INDEX [IDX_OWNER_USER_ID] ON [LAB_EXCEL_IMPORT_TEMPLATE] ([F_OWNER_USER_ID]);
*/

-- ============================================
-- PostgreSQL版本
-- ============================================

/*
-- 1. Excel导入模板表
CREATE TABLE IF NOT EXISTS "LAB_EXCEL_IMPORT_TEMPLATE" (
    "F_Id" VARCHAR(50) NOT NULL PRIMARY KEY,
    "F_TEMPLATE_NAME" VARCHAR(100) NOT NULL,
    "F_TEMPLATE_CODE" VARCHAR(50) NOT NULL,
    "F_DESCRIPTION" VARCHAR(500) NULL,
    "F_TEMPLATE_TYPE" VARCHAR(20) NOT NULL DEFAULT 'system',
    "F_OWNER_USER_ID" VARCHAR(50) NULL,
    "F_CONFIG_JSON" TEXT NULL,
    "F_PRODUCT_SPEC_ID" VARCHAR(50) NULL,
    "F_VERSION" INT NOT NULL DEFAULT 1,
    "F_IS_DEFAULT" INT NOT NULL DEFAULT 0,
    "F_SORTCODE" BIGINT NULL,
    "F_CREATORUSERID" VARCHAR(50) NULL,
    "F_CREATORTIME" TIMESTAMP NULL,
    "F_LASTMODIFYUSERID" VARCHAR(50) NULL,
    "F_LASTMODIFYTIME" TIMESTAMP NULL,
    "F_DELETEMARK" INT NULL,
    "F_DELETETIME" TIMESTAMP NULL,
    "F_DELETEUSERID" VARCHAR(50) NULL,
    "F_TENANTID" VARCHAR(50) NULL,
    CONSTRAINT "UK_TEMPLATE_CODE" UNIQUE ("F_TEMPLATE_CODE", "F_DELETEMARK")
);

CREATE INDEX "IDX_TEMPLATE_TYPE" ON "LAB_EXCEL_IMPORT_TEMPLATE" ("F_TEMPLATE_TYPE");
CREATE INDEX "IDX_PRODUCT_SPEC_ID" ON "LAB_EXCEL_IMPORT_TEMPLATE" ("F_PRODUCT_SPEC_ID");
CREATE INDEX "IDX_IS_DEFAULT" ON "LAB_EXCEL_IMPORT_TEMPLATE" ("F_IS_DEFAULT");
CREATE INDEX "IDX_DELETEMARK" ON "LAB_EXCEL_IMPORT_TEMPLATE" ("F_DELETEMARK");
CREATE INDEX "IDX_OWNER_USER_ID" ON "LAB_EXCEL_IMPORT_TEMPLATE" ("F_OWNER_USER_ID");
*/