-- ============================================
-- 指标引擎数据库表创建脚本
-- 数据库类型：MySQL
-- 创建日期：2026-01-27
-- 说明：创建指标定义、变量绑定、公式版本、计算结果四张核心表
-- ============================================

-- ============================================
-- 1. 指标定义表（LAB_INDICATOR_DEFINITION）
-- ============================================
CREATE TABLE IF NOT EXISTS `LAB_INDICATOR_DEFINITION` (
    -- 基础字段（从CLDEntityBase继承）
    `F_ID` VARCHAR(50) NOT NULL COMMENT '主键ID',
    `F_TENANTID` VARCHAR(50) DEFAULT NULL COMMENT '租户ID',
    `F_CREATORTIME` DATETIME DEFAULT NULL COMMENT '创建时间',
    `F_CREATORUSERID` VARCHAR(50) DEFAULT NULL COMMENT '创建用户ID',
    `F_ENABLEDMARK` INT DEFAULT 1 COMMENT '启用标识（1-启用，0-禁用）',
    `F_LastModifyTime` DATETIME DEFAULT NULL COMMENT '修改时间',
    `F_LastModifyUserId` VARCHAR(50) DEFAULT NULL COMMENT '修改用户ID',
    `F_DeleteMark` INT DEFAULT 0 COMMENT '删除标志（0-未删除，1-已删除）',
    `F_DeleteTime` DATETIME DEFAULT NULL COMMENT '删除时间',
    `F_DeleteUserId` VARCHAR(50) DEFAULT NULL COMMENT '删除用户ID',
    
    -- 业务字段
    `F_INDICATOR_NAME` VARCHAR(100) NOT NULL COMMENT '指标名称（如：一米带材重量）',
    `F_INDICATOR_CODE` VARCHAR(100) NOT NULL COMMENT '指标编码（如：ONE_METER_WT）',
    `F_DESCRIPTION` VARCHAR(500) DEFAULT NULL COMMENT '指标描述',
    `F_DATA_TYPE` VARCHAR(20) NOT NULL DEFAULT 'DECIMAL' COMMENT '数据类型：DECIMAL/INT/TEXT',
    `F_FORMULA_EXPRESSION` VARCHAR(2000) NOT NULL COMMENT '公式表达式',
    `F_FORMULA_LANGUAGE` VARCHAR(20) NOT NULL DEFAULT 'EXCEL' COMMENT '公式语言：EXCEL/MATH/SCRIPT',
    `F_CALCULATION_ORDER` INT NOT NULL DEFAULT 0 COMMENT '计算顺序（解决依赖）',
    `F_UNIT_ID` VARCHAR(50) DEFAULT NULL COMMENT '单位ID（关联LAB_UNIT）',
    `F_PRECISION` INT DEFAULT NULL COMMENT '小数位数',
    `F_IS_ENABLED` BIT NOT NULL DEFAULT 1 COMMENT '是否启用',
    `F_IS_SYSTEM` BIT NOT NULL DEFAULT 0 COMMENT '是否为系统内置指标',
    `F_SORTCODE` BIGINT DEFAULT NULL COMMENT '排序码',
    
    PRIMARY KEY (`F_ID`),
    UNIQUE KEY `IDX_INDICATOR_CODE` (`F_INDICATOR_CODE`, `F_TENANTID`),
    KEY `IDX_INDICATOR_ENABLED` (`F_IS_ENABLED`, `F_TENANTID`),
    KEY `IDX_INDICATOR_ORDER` (`F_CALCULATION_ORDER`, `F_TENANTID`),
    KEY `IDX_TENANT_ID` (`F_TENANTID`),
    KEY `IDX_DELETE_MARK` (`F_DeleteMark`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='指标定义表';

-- ============================================
-- 2. 公式变量绑定表（LAB_INDICATOR_VARIABLE）
-- ============================================
CREATE TABLE IF NOT EXISTS `LAB_INDICATOR_VARIABLE` (
    -- 基础字段（从CLDEntityBase继承）
    `F_ID` VARCHAR(50) NOT NULL COMMENT '主键ID',
    `F_TENANTID` VARCHAR(50) DEFAULT NULL COMMENT '租户ID',
    `F_CREATORTIME` DATETIME DEFAULT NULL COMMENT '创建时间',
    `F_CREATORUSERID` VARCHAR(50) DEFAULT NULL COMMENT '创建用户ID',
    `F_ENABLEDMARK` INT DEFAULT 1 COMMENT '启用标识（1-启用，0-禁用）',
    `F_LastModifyTime` DATETIME DEFAULT NULL COMMENT '修改时间',
    `F_LastModifyUserId` VARCHAR(50) DEFAULT NULL COMMENT '修改用户ID',
    `F_DeleteMark` INT DEFAULT 0 COMMENT '删除标志（0-未删除，1-已删除）',
    `F_DeleteTime` DATETIME DEFAULT NULL COMMENT '删除时间',
    `F_DeleteUserId` VARCHAR(50) DEFAULT NULL COMMENT '删除用户ID',
    
    -- 业务字段
    `F_INDICATOR_ID` VARCHAR(50) NOT NULL COMMENT '指标ID',
    `F_VARIABLE_NAME` VARCHAR(100) NOT NULL COMMENT '变量名称（公式中使用）',
    `F_SOURCE_TYPE` VARCHAR(20) NOT NULL COMMENT '来源类型：COLUMN/DIMENSION/CONSTANT',
    `F_SOURCE_ID` VARCHAR(100) DEFAULT NULL COMMENT '来源ID（列名/维度ID/常量值）',
    `F_DATA_TYPE` VARCHAR(20) NOT NULL COMMENT '数据类型',
    `F_IS_REQUIRED` BIT NOT NULL DEFAULT 1 COMMENT '是否必需',
    `F_DEFAULT_VALUE` VARCHAR(200) DEFAULT NULL COMMENT '默认值',
    `F_SORTCODE` BIGINT DEFAULT NULL COMMENT '排序码',
    
    PRIMARY KEY (`F_ID`),
    KEY `IDX_VARIABLE_INDICATOR` (`F_INDICATOR_ID`, `F_TENANTID`),
    KEY `IDX_TENANT_ID` (`F_TENANTID`),
    KEY `IDX_DELETE_MARK` (`F_DeleteMark`),
    CONSTRAINT `FK_VARIABLE_INDICATOR` FOREIGN KEY (`F_INDICATOR_ID`) REFERENCES `LAB_INDICATOR_DEFINITION` (`F_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='公式变量绑定表';

-- ============================================
-- 3. 公式版本表（LAB_INDICATOR_FORMULA_VERSION）
-- ============================================
CREATE TABLE IF NOT EXISTS `LAB_INDICATOR_FORMULA_VERSION` (
    -- 基础字段（从CLDEntityBase继承）
    `F_ID` VARCHAR(50) NOT NULL COMMENT '主键ID',
    `F_TENANTID` VARCHAR(50) DEFAULT NULL COMMENT '租户ID',
    `F_CREATORTIME` DATETIME DEFAULT NULL COMMENT '创建时间',
    `F_CREATORUSERID` VARCHAR(50) DEFAULT NULL COMMENT '创建用户ID',
    `F_ENABLEDMARK` INT DEFAULT 1 COMMENT '启用标识（1-启用，0-禁用）',
    `F_LastModifyTime` DATETIME DEFAULT NULL COMMENT '修改时间',
    `F_LastModifyUserId` VARCHAR(50) DEFAULT NULL COMMENT '修改用户ID',
    `F_DeleteMark` INT DEFAULT 0 COMMENT '删除标志（0-未删除，1-已删除）',
    `F_DeleteTime` DATETIME DEFAULT NULL COMMENT '删除时间',
    `F_DeleteUserId` VARCHAR(50) DEFAULT NULL COMMENT '删除用户ID',
    
    -- 业务字段
    `F_INDICATOR_ID` VARCHAR(50) NOT NULL COMMENT '指标ID',
    `F_VERSION` INT NOT NULL COMMENT '版本号（从1开始）',
    `F_VERSION_NAME` VARCHAR(100) DEFAULT NULL COMMENT '版本名称（v1.0, v2.0）',
    `F_FORMULA_EXPRESSION` VARCHAR(2000) NOT NULL COMMENT '公式表达式（历史版本）',
    `F_CHANGE_REASON` VARCHAR(500) DEFAULT NULL COMMENT '变更原因',
    `F_IS_CURRENT` BIT NOT NULL DEFAULT 0 COMMENT '是否为当前版本',
    `F_VERSION_CREATE_TIME` DATETIME DEFAULT NULL COMMENT '版本创建时间',
    `F_VERSION_CREATOR_ID` VARCHAR(50) DEFAULT NULL COMMENT '版本创建者ID',
    
    PRIMARY KEY (`F_ID`),
    KEY `IDX_VERSION_INDICATOR` (`F_INDICATOR_ID`),
    KEY `IDX_VERSION_CURRENT` (`F_IS_CURRENT`),
    KEY `IDX_TENANT_ID` (`F_TENANTID`),
    KEY `IDX_DELETE_MARK` (`F_DeleteMark`),
    CONSTRAINT `FK_VERSION_INDICATOR` FOREIGN KEY (`F_INDICATOR_ID`) REFERENCES `LAB_INDICATOR_DEFINITION` (`F_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='公式版本表';

-- ============================================
-- 4. 指标计算结果表（LAB_INDICATOR_RESULT）
-- ============================================
CREATE TABLE IF NOT EXISTS `LAB_INDICATOR_RESULT` (
    -- 基础字段（从CLDEntityBase继承）
    `F_ID` VARCHAR(50) NOT NULL COMMENT '主键ID',
    `F_TENANTID` VARCHAR(50) DEFAULT NULL COMMENT '租户ID',
    `F_CREATORTIME` DATETIME DEFAULT NULL COMMENT '创建时间',
    `F_CREATORUSERID` VARCHAR(50) DEFAULT NULL COMMENT '创建用户ID',
    `F_ENABLEDMARK` INT DEFAULT 1 COMMENT '启用标识（1-启用，0-禁用）',
    `F_LastModifyTime` DATETIME DEFAULT NULL COMMENT '修改时间',
    `F_LastModifyUserId` VARCHAR(50) DEFAULT NULL COMMENT '修改用户ID',
    `F_DeleteMark` INT DEFAULT 0 COMMENT '删除标志（0-未删除，1-已删除）',
    `F_DeleteTime` DATETIME DEFAULT NULL COMMENT '删除时间',
    `F_DeleteUserId` VARCHAR(50) DEFAULT NULL COMMENT '删除用户ID',
    
    -- 业务字段
    `F_INTERMEDIATE_DATA_ID` VARCHAR(50) NOT NULL COMMENT '中间数据ID',
    `F_INDICATOR_CODE` VARCHAR(100) NOT NULL COMMENT '指标编码',
    `F_CALCULATED_VALUE` VARCHAR(200) DEFAULT NULL COMMENT '计算结果',
    `F_CALCULATION_TIME` DATETIME NOT NULL COMMENT '计算时间',
    `F_FORMULA_VERSION` INT NOT NULL COMMENT '使用的公式版本',
    `F_CALCULATION_STATUS` VARCHAR(20) DEFAULT NULL COMMENT '计算状态：SUCCESS/ERROR',
    `F_ERROR_MESSAGE` VARCHAR(1000) DEFAULT NULL COMMENT '错误信息',
    
    PRIMARY KEY (`F_ID`),
    KEY `IDX_RESULT_DATA_INDICATOR` (`F_INTERMEDIATE_DATA_ID`, `F_INDICATOR_CODE`),
    KEY `IDX_RESULT_TIME` (`F_CALCULATION_TIME`),
    KEY `IDX_TENANT_ID` (`F_TENANTID`),
    KEY `IDX_DELETE_MARK` (`F_DeleteMark`),
    KEY `IDX_CALCULATION_STATUS` (`F_CALCULATION_STATUS`),
    CONSTRAINT `FK_RESULT_INTERMEDIATE_DATA` FOREIGN KEY (`F_INTERMEDIATE_DATA_ID`) REFERENCES `LAB_INTERMEDIATE_DATA` (`F_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='指标计算结果表';
