-- 产品定义版本管理数据库迁移脚本
-- 创建时间：2026-01-13
-- 描述：添加产品规格版本管理功能所需的表和字段

-- 1. 创建产品规格版本表
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='LAB_PRODUCT_SPEC_VERSION' AND xtype='U')
BEGIN
    CREATE TABLE LAB_PRODUCT_SPEC_VERSION (
        F_ID NVARCHAR(50) NOT NULL PRIMARY KEY,
        F_PRODUCT_SPEC_ID NVARCHAR(50) NOT NULL,
        F_VERSION INT NOT NULL DEFAULT 1,
        F_VERSION_NAME NVARCHAR(100),
        F_VERSION_DESCRIPTION NVARCHAR(500),
        F_IS_CURRENT INT NOT NULL DEFAULT 0, -- 1: 当前版本, 0: 历史版本
        F_CREATOR_TIME DATETIME NOT NULL,
        F_CREATOR_USER_ID NVARCHAR(50),
        F_LAST_MODIFY_TIME DATETIME,
        F_LAST_MODIFY_USER_ID NVARCHAR(50),
        F_DELETE_MARK INT DEFAULT 0,
        F_DELETE_TIME DATETIME,
        F_DELETE_USER_ID NVARCHAR(50),
        INDEX IX_PRODUCT_SPEC_VERSION_PRODUCT_SPEC_ID (F_PRODUCT_SPEC_ID),
        INDEX IX_PRODUCT_SPEC_VERSION_IS_CURRENT (F_IS_CURRENT)
    );
END

-- 2. 修改产品规格扩展属性表，添加版本字段
IF NOT EXISTS (SELECT * FROM syscolumns WHERE id=object_id('LAB_PRODUCT_SPEC_ATTRIBUTE') AND name='F_VERSION')
BEGIN
    ALTER TABLE LAB_PRODUCT_SPEC_ATTRIBUTE ADD F_VERSION INT DEFAULT 1;

    -- 为现有数据设置默认版本
    UPDATE LAB_PRODUCT_SPEC_ATTRIBUTE SET F_VERSION = 1 WHERE F_VERSION IS NULL;
END

IF NOT EXISTS (SELECT * FROM syscolumns WHERE id=object_id('LAB_PRODUCT_SPEC_ATTRIBUTE') AND name='F_VERSION_CREATE_TIME')
BEGIN
    ALTER TABLE LAB_PRODUCT_SPEC_ATTRIBUTE ADD F_VERSION_CREATE_TIME DATETIME;
END

IF NOT EXISTS (SELECT * FROM syscolumns WHERE id=object_id('LAB_PRODUCT_SPEC_ATTRIBUTE') AND name='F_VERSION_DESCRIPTION')
BEGIN
    ALTER TABLE LAB_PRODUCT_SPEC_ATTRIBUTE ADD F_VERSION_DESCRIPTION NVARCHAR(500);
END

-- 3. 修改中间数据表，添加产品规格版本字段
IF NOT EXISTS (SELECT * FROM syscolumns WHERE id=object_id('LAB_INTERMEDIATE_DATA') AND name='F_PRODUCT_SPEC_VERSION')
BEGIN
    ALTER TABLE LAB_INTERMEDIATE_DATA ADD F_PRODUCT_SPEC_VERSION INT;

    -- 为现有数据设置默认版本
    UPDATE LAB_INTERMEDIATE_DATA SET F_PRODUCT_SPEC_VERSION = 1 WHERE F_PRODUCT_SPEC_VERSION IS NULL;
END

-- 4. 创建初始版本记录（为已存在的产品规格）
IF NOT EXISTS (SELECT * FROM LAB_PRODUCT_SPEC_VERSION WHERE F_VERSION = 1)
BEGIN
    INSERT INTO LAB_PRODUCT_SPEC_VERSION (
        F_ID, F_PRODUCT_SPEC_ID, F_VERSION, F_VERSION_NAME,
        F_VERSION_DESCRIPTION, F_IS_CURRENT, F_CREATOR_TIME,
        F_CREATOR_USER_ID
    )
    SELECT
        NEWID(), F_ID, 1, 'v1.0',
        '初始版本', 1, GETDATE(),
        'system'
    FROM LAB_PRODUCT_SPEC
    WHERE F_DELETE_MARK = 0 OR F_DELETE_MARK IS NULL;
END

-- 5. 更新索引
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_PRODUCT_SPEC_ATTRIBUTE_VERSION')
BEGIN
    CREATE INDEX IX_PRODUCT_SPEC_ATTRIBUTE_VERSION ON LAB_PRODUCT_SPEC_ATTRIBUTE (F_PRODUCT_SPEC_ID, F_VERSION);
END

-- 6. 创建版本管理相关的存储过程（可选）
-- 获取产品规格当前版本
IF EXISTS (SELECT * FROM sysobjects WHERE name='sp_GetProductSpecCurrentVersion' AND xtype='P')
    DROP PROCEDURE sp_GetProductSpecCurrentVersion;
GO

CREATE PROCEDURE sp_GetProductSpecCurrentVersion
    @ProductSpecId NVARCHAR(50)
AS
BEGIN
    SELECT TOP 1 F_VERSION
    FROM LAB_PRODUCT_SPEC_VERSION
    WHERE F_PRODUCT_SPEC_ID = @ProductSpecId
    AND F_IS_CURRENT = 1
    AND (F_DELETE_MARK = 0 OR F_DELETE_MARK IS NULL)
    ORDER BY F_VERSION DESC;
END
GO

-- 7. 数据完整性检查
-- 确保所有产品规格都有当前版本
UPDATE LAB_PRODUCT_SPEC_VERSION
SET F_IS_CURRENT = 1
WHERE F_VERSION = 1
AND F_ID IN (
    SELECT MIN(F_ID)
    FROM LAB_PRODUCT_SPEC_VERSION
    WHERE F_PRODUCT_SPEC_ID IN (
        SELECT F_ID FROM LAB_PRODUCT_SPEC
        WHERE F_DELETE_MARK = 0 OR F_DELETE_MARK IS NULL
    )
    GROUP BY F_PRODUCT_SPEC_ID
);

-- 8. 清理重复版本（保留最高版本号为当前版本）
UPDATE LAB_PRODUCT_SPEC_VERSION
SET F_IS_CURRENT = 0
WHERE F_ID NOT IN (
    SELECT F_ID FROM (
        SELECT F_ID, ROW_NUMBER() OVER (PARTITION BY F_PRODUCT_SPEC_ID ORDER BY F_VERSION DESC) AS rn
        FROM LAB_PRODUCT_SPEC_VERSION
        WHERE F_IS_CURRENT = 1
    ) t WHERE rn = 1
);

PRINT '产品定义版本管理数据库迁移脚本执行完成';